config/routes.rb
Rails.application.routes.draw do
 
  get 'sessions/new'

  root 'static_pages#home'
  
  get  '/paint',    to: 'static_pages#paint'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :microposts,          only: [:create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size

  private

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def feed
    Micropost.where("user_id = ?", id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Blog created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Blog deleted"
    redirect_to request.referrer || root_url
  end

private

  def micropost_params
      params.require(:micropost).permit(:content, :picture)
  end
    
  def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination. Try Again!'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def paint
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index
     @users = User.paginate(page: params[:page])
  end
  
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Mayberry Grove! We hope you enjoy our site!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = " Congrats your profile has been updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

private

  def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end
    
  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Mayberry Grove"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def log_in(user)
    session[:user_id] = user.id
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://finalprojectt-lharvey.c9users.io/">Mayberry Grove</a>
    by Lauren Harvey
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Mayberry Grove", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Paint", paint_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
     <%= render 'layouts/header' %>
     <%= image_tag 'mayberrylogo.jpg', class:"image1", style: 'height: 10; align: center', alt: 'mayberry logo' %>
    <div class="container">
        <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new blog post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<h1>Want to know more about us?</h1>
<p> 
   Our southern vintage company welcomes you to come and explore our site!  We offer an amazing selection of paints!
   We have a bunch of items on our site for you to enjoy!  
   Mayberry Grove first started in the small southern state  South Carolina! 
   We only have been opened for a few weeks and we already starting to grow such as adding more products! 
   Displayed below is a list of our hours! Feel free to call us or email us at anytime! 
   As we care deeply about our customers! 
   For more information please visit our Contact page where you can contact us personally! 
   Happy Shopping! 
</p> 
<h1>Store Hours</h1> 
<table> 
   <tr> 
      <th>Day</th> 
      <th>Time</th> 
   </tr> 
   <tr> 
      <td>Monday-Wednesday</td> 
      <td>8:00am - 7:00pm</td> 
   </tr> 
   <tr> 
      <td>Thursday</td> 
      <td>9:00am - 7:00pm</td> 
   </tr> 
   <tr> 
      <td>Friday-Saturday</td> 
      <td>10:00am - 9:00pm</td> 
   </tr> 
   <tr> 
      <td>Sunday</td> 
      <td>Closed</td> 
   </tr> 
</table> 

app/views/static_pages/contact.html.erb
<h1>Contact us!</h1>
    <%= image_tag 'contactus.png', class:"image1", style: 'height: 10; align: center', alt: 'mayberry logo' %>
<p>
    <br> Hello our company is more than willing to help you with 
     anything that you may need. Our services are open 24/7<br><br><br>
  
  
        Email: mayberrygrove@yahoo.com<br><br><br>
 
        Phone: 843-777-0987<br><br><br>
 
       Chat: We are sorry our Chat room is currently out of service.<br>
       Please email or call us if you need any instance.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
     <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  
  <div class="center jumbotron">
    <h1>Welcome to Mayberry Grove</h1>

    <h3>
      <p>Click the button below & Sign up now to become a member.</p>

      <button onclick="myFunction()">Please Click me</button>

      <p id="demo"></p>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary signupbtn" %>
      <%= image_tag 'flowers.jpg', style: 'height: 50; align: center', alt: 'flowers pic' %>
    </h3>
  </div>
  
  <h4>Sneak Peak of NEW Items coming soon!</h4>
  
<div class="gallery">
  <a target="_blank" href="productone.jpg">
     <%= image_tag "productone.jpg", width:"300", height:"200" %>
  </a>
  <div class="desc">Vintage Blackboard $40.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="producttwo.jpg">
     <%= image_tag "producttwo.jpg", width:"300", height:"200" %>
  </a>
  <div class="desc">Vintage Cup Rack $25.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="productthree.jpg">
    <%= image_tag "productthree.jpg", width:"300", height:"200" %>
  </a>
  <div class="desc">Vintage Bread Board $35.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="productfour.jpg">
    <%= image_tag "productfour.jpg", width:"300", height:"200" %>
  </a>
  <div class="desc">Vintage Wall Clock $35.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="productfive.jpg">
    <%= image_tag "productfive.jpg", width:"300", height:"200" %>
  </a>
  <div class="desc">Wodden Plate Holder $15.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="productsix.jpg">
    <%= image_tag "productsix.jpg", width:"300", height:"200" %>
  </a>
  <div class="desc">Wodden Crate & Glasses $75.00</div>
</div>
<% end %>

app/views/static_pages/paint.html.erb
<h1>Welcome to our Paints</h1>
  <%= image_tag 'paints.png', class:"image1", style: 'height: 10; align: center', alt: 'paints' %>
<body>
  
    
<h2>Popular Paints</h2>

<div class="gallery">
  <a target="_blank" href="morningcalm.png">
     <%= image_tag "morningcalm.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Morning Calm  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="underthestars.png">
     <%= image_tag "underthestars.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Under the Stars  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="stormchaser.png">
     <%= image_tag "stormchaser.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Storm Chaser  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="midnightstorm.png">
    <%= image_tag "midnightstorm.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Midnight Storm  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="plum.png">
    <%= image_tag "plum.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Plum Rocks  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="perwinkle.png">
    <%= image_tag "perwinkle.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Perwinkle Nook  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="sunset.png">
     <%= image_tag "sunset.png", width:"300", height:"200" %>
  </a>
  <div class="desc"> Name: Sunset Slate   Half a gallon: $5.00  Gallon: $10.00</div>
</div> 

<div class="gallery">
  <a target="_blank" href="pinklemonade.png">
     <%= image_tag "pinklemonade.png", width:"300", height:"200" %>
  </a>
  <div class="desc"> Name: Pink Lemonade Half a gallon: $5.00  Gallon: $10.00</div>
</div>

 <hr class="style1">
 
 <div class="gallery">
  <a target="_blank" href="cottagefeel.png">
     <%= image_tag "cottagefeel.png", width:"300", height:"200" %>
  </a>
  <div class="desc"> Name: Cottage Feel  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="lemony.png">
     <%= image_tag "lemony.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Lemony Twist   Half a gallon: $5.00  Gallon: $10.00</div>
</div>
 
<div class="gallery">
  <a target="_blank" href="magnoliagreen.png">
     <%= image_tag "magnoliagreen.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Magnolia Green Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="aspenleaf.png">
     <%= image_tag "aspenleaf.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Aspen Leafs Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<h2>New Pastel Paints</h2>

<div class="gallery">
  <a target="_blank" href="popofcolor.png">
     <%= image_tag "popofcolor.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Pop of Color  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="softlinen.png">
     <%= image_tag "softlinen.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Softs Linen Tan Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="pinacotta.png">
     <%= image_tag "pinacotta.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Pina Cottas Ace  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="cloudygray.png">
     <%= image_tag "cloudygray.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Cloudy Gray Renewed   Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="ellarose.png">
     <%= image_tag "ellarose.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Ella B. Roses   Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="burntsun.png">
     <%= image_tag "burntsun.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Burnt Sunset  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<h2>Dark Vintage Paints</h2>

<div class="gallery">
  <a target="_blank" href="braveandbold.png">
     <%= image_tag "braveandbold.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Brave & Bold  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="ripetomato.png">
     <%= image_tag "ripetomato.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Ripe Tomatos  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="goldendust.png">
     <%= image_tag "goldendust.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Golden Dusts  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="weekend.png">
     <%= image_tag "weekend.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Weekend Fun  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="inbloomseason.png">
     <%= image_tag "inbloomseason.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Bloom Season  Half a gallon: $5.00  Gallon: $10.00</div>
</div>

<div class="gallery">
  <a target="_blank" href="bloomydaygray.png">
     <%= image_tag "bloomydaygray.png", width:"300", height:"200" %>
  </a>
  <div class="desc">Name: Bloomy Day  Half a gallon: $5.00  Gallon: $10.00</div>
</div>




</body>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails">change</a>
    </div>
  </div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
   </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>